### ISSUE TITLE
GUI: Main menu design

### ISSUE THREAD

**Issue by martin-azpillaga** [jgirald/ES2015F#10]
sketch design of the main menu. Should contain detailed layout options:
- Horizontal, vertical or grid groups
- Margins and padding
- GUI Theme: colours, textures etc. to be shared in all sebsequent menus.

**Comment by martin-azpillaga** [comment]
Attach preview image before closing the issue.

**Comment by laianad** [comment]
![menu](https://cloud.githubusercontent.com/assets/10979454/10268082/b1cbf218-6aad-11e5-99f0-19246a513f31.png)
