### ISSUE TITLE
Coordination: Communicate with other teams

### ISSUE THREAD

**Issue by martin-azpillaga** [jgirald/ES2015F#17]
Mostly communicate with the Team D members to structure the code correctly and prevent any big conflict.

**Comment by martin-azpillaga** [comment]
Conclusions can be added as comments of this issue.

**Comment by sqmath** [comment]
This was assigned to me, for this sprint

**Comment by sqmath** [comment]
Doubts asked to product owner and certain problems discussed with other teams. 

Conclusions with the Product Owner:
Main civil unit, citizen, can recollect everything. Specialized units can only recollect their specialized resource, but faster.
Civil units can attack, but military units can't recollect.
For the moment, all civil units will be created in the main civil unit, but later in the development they will be created in their respective buildings. The same for the military units.

In the main civil building, you can pay for research which will give benefits such as increased speed on construction.

Minimap: there should appear movement of units in visible areas, and special effects whenever an attack starts somewhere visible.
