### ISSUE TITLE
Bug fix: Unit creation

### ISSUE THREAD

**Issue by martin-azpillaga** [jgirald/ES2015F#242]
### Description:

Modify the unit creation code so that lets the AI create its units correctly. Don't spawn multiple units at the same place so that the user can select the unit he/she wants without problems.

### Definition of done:

- [x] The AI creates units over time automatically
- [x] When multiple units are created consecutively each one is positioned in a diferent location

#### Estimated effort: 2

**Comment by ccortes492** [comment]
Update de la situación del bug?

**Comment by martin-azpillaga** [comment]
Incluía ese error y ya está solucionado. Lo he arreglado junto con @bernatdelsanto y él se encargará de integrarlo.
Era problema de tags, que se llamaba a métodos de actualizar el HUD cuando algo era creado por la CPU y se quedaba pillado.
