### ISSUE TITLE
IA  counterattack.

### ISSUE THREAD

**Issue by czs92** [jgirald/ES2015F#269]
### Description:

The aim of this modul is the counterattack of the IA, that includes trying to counteract the player's progress to win condition.

### Effordance:

This is an epic issue, it will be splitted in different issues.

This issue it will be used to communication with team C.

**Comment by czs92** [comment]
Dear team C (@martin-azpillaga, @laianad, @sqmath, @MarcBeltran @SergiCebrianGres ) I need to know the win conditions of the game, as soon as possible. 
The win conditions of the menu are different from the win condition in Victory.cs. 
- Which ones are the correct ones?
- What's the meaning of each one (I mean how I can accomplish the win condition)?

Thanks

**Comment by sqmath** [comment]
Hi czs92, 

* The correct ones are those written in Victory.cs. Main Menu will be updated to match those values.
* The meaning of each win condition is the following:
    * Wonder: build a Wonder to win.
    * MapControl: control all tower objectives in the map for one whole minute to win.
    * Annihilation: destroy every building from the enemy to win.

Take into account that more than one condition could be applied, meaning that if at any time at least one of them is fulfilled, it will be considered an endgame.

I hope that clarifies it.
