### ISSUE TITLE
Building sounds

### ISSUE THREAD

**Issue by andresvara04** [jgirald/ES2015F#290]
Description: Add sound for buildings construction.

DONE: add sounds to the following phases of construction:
[] New building
[] Building complete
[] Building upgrade

**Comment by Jabelriera** [comment]
Si me lo asignáis a mi la DOD debería ser crear los sonidos y añadirlos al directorio correspondiente del repositorio. Añadirlos a la fase de construcción es cosa del Team C/D.

**Comment by Jabelriera** [comment]
Us en poso també un de destruccio? I un en flames?

**Comment by Jabelriera** [comment]
Hecho. De momento está en la rama S5 del Team A.
