### ISSUE TITLE
Wonder counterattack

### ISSUE THREAD

**Issue by czs92** [jgirald/ES2015F#314]
### Description:

The CPU attacks the wonder when player tries to build it

### Definition of DONE:

- [x] CPU attacks the wonder when player is building it

### Effordance: 3

**Comment by czs92** [comment]
Currently, it's not possible to know if a wonder is being constructed. 
So, the issue is stopped until Team C ( @sqmath @laianad @martin-azpillaga @SergiCebrianGres @MarcBeltran ) change that.

**Comment by laianad** [comment]
In the script construct you have the variables inConstruction and buildingToConstruct that can solve your problem.
@czs92
