### ISSUE TITLE
Buildings Sound Effects

### ISSUE THREAD

**Issue by olga89** [jgirald/ES2015F#89]
Començar a investigar com afegir effectes sonors als edificis i anar afegint-los

**Comment by Jabelriera** [comment]
A santo de que me asignas esto? Mi tarea fue grabarlos y ya lo hice como se puede ver en el issue correspondiente. Fue hace 2 Sprints.

**Comment by olga89** [comment]
sons del foc per a la fase de "destruction" grabats per un membre del team A.
